Update merge.yml

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -1,23 +1,50 @@
- name: Merge Pull Request
- on:
-   workflow_run:
-     workflows: ["Create Pull Request"]
-     types: [completed] #requested
-   workflow_dispatch:
+name: Auto-Approve and Merge
 
- jobs:
-   merge_pull_request:
+on:
+  pull_request:
+    types:
+      - opened
+
+jobs:
+  auto_approve_and_merge:
     runs-on: ubuntu-latest
-    steps:
-  
-    - name: Checkout code
-      uses: actions/checkout@v2
-      
-    - name: "Approve pull request"
-      uses: "actions/github-script@v5"
-      with:
-        github-token: "${{ secrets.GITHUB_TOKEN }}"
-        script: |
-          const pullRequest = context.payload.workflow_run.pull_requests[0]
-          console.log(pullRequest.number)
 
+    steps:
+      - name: Check if PR is Mergeable
+        run: |
+          # Check if the pull request is mergeable
+          PR_NUMBER=${{ github.event.pull_request.number }}
+          IS_MERGEABLE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.mergeable')
+
+          if [ "$IS_MERGEABLE" = "true" ]; then
+            echo "Pull Request is mergeable."
+          else
+            echo "Pull Request is not mergeable."
+            exit 1
+          fi
+
+      - name: Auto-Approve PR
+        run: |
+          # Approve the pull request
+          PR_NUMBER=${{ github.event.pull_request.number }}
+          REVIEW_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X POST -d '{"event": "APPROVE"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" | jq -r '.id')
+
+          if [ -n "$REVIEW_ID" ]; then
+            echo "Pull Request approved."
+          else
+            echo "Failed to approve the pull request."
+            exit 1
+          fi
+
+      - name: Merge PR
+        run: |
+          # Merge the pull request
+          PR_NUMBER=${{ github.event.pull_request.number }}
+          MERGE_RESULT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X PUT "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge")
+
+          if [[ "$MERGE_RESULT" == *"merged"* ]]; then
+            echo "Pull Request merged."
+          else
+            echo "Failed to merge the pull request."
+            exit 1
+          fi
